//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Scripts/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/PlayerInputs.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GolfControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GolfControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""PlayerGeneral"",
            ""id"": ""a7525ea3-4ea8-496d-a845-f097914bbde3"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""84d885ff-c238-463b-8381-53d91f9b674e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StartGolfing"",
                    ""type"": ""Button"",
                    ""id"": ""10ec02fd-2e4f-4586-9402-e42dcf05e24f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mantle"",
                    ""type"": ""Button"",
                    ""id"": ""c926bc4c-3181-4fe3-82e4-d8fef99dc120"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7b5c58e4-1dbe-4a94-b04d-fd478e8f1c1e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""edb0dab9-7fca-4f9a-9331-bc9904d7911c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4786d143-e49e-4c32-a3e6-ab13ed5e24d7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b0d2b9c9-f038-47d8-b95d-9a42f496b49d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""501326df-f788-4b10-a155-81fa579b4d9a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d052ae3c-94d3-4766-893d-8d05087a6e15"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""StartGolfing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51c7ad88-94d4-446c-8e8e-3eeaaf80f0c1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""Mantle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GolfSwing"",
            ""id"": ""71b98fa0-9b1f-49fb-a41c-8c5dc75a23a9"",
            ""actions"": [
                {
                    ""name"": ""Swing"",
                    ""type"": ""Button"",
                    ""id"": ""5b616892-7404-4b0e-ad76-224a4c97a28f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PracticeSwing"",
                    ""type"": ""Button"",
                    ""id"": ""ab88c800-0402-46e9-8534-1a2f944b3583"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""9e978672-2b15-4636-9dbe-e9e7b84fa0b9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StopGolfing"",
                    ""type"": ""Button"",
                    ""id"": ""d469129e-75cb-473b-a73a-b6ce3cf7f2c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""0aca5da1-4c2e-4c7c-9239-61e35e5df9a4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""f6823b29-b4f1-4678-897d-d9c83f7db49a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4b0aeead-9266-4c45-968c-e149b5d9ac08"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""Swing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""845aafcf-6158-47f1-b4de-7b1978bf2e1b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""PracticeSwing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""A and D"",
                    ""id"": ""83c55799-6eaf-456d-8dd4-9e620d04a58f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""704e82c3-3790-4988-9bdb-29f4a8010925"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""992f2822-b753-4964-89ad-1f70fa58f86b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""946a015d-b363-4807-be8e-c86b130b0aae"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""StopGolfing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86d15e3f-bd44-42e5-aaf7-92b98abfc0b7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardAndMouse"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec338f64-8002-4599-9e59-fb1f9e51adf5"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardAndMouse"",
            ""bindingGroup"": ""KeyboardAndMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerGeneral
        m_PlayerGeneral = asset.FindActionMap("PlayerGeneral", throwIfNotFound: true);
        m_PlayerGeneral_Move = m_PlayerGeneral.FindAction("Move", throwIfNotFound: true);
        m_PlayerGeneral_StartGolfing = m_PlayerGeneral.FindAction("StartGolfing", throwIfNotFound: true);
        m_PlayerGeneral_Mantle = m_PlayerGeneral.FindAction("Mantle", throwIfNotFound: true);
        // GolfSwing
        m_GolfSwing = asset.FindActionMap("GolfSwing", throwIfNotFound: true);
        m_GolfSwing_Swing = m_GolfSwing.FindAction("Swing", throwIfNotFound: true);
        m_GolfSwing_PracticeSwing = m_GolfSwing.FindAction("PracticeSwing", throwIfNotFound: true);
        m_GolfSwing_Rotate = m_GolfSwing.FindAction("Rotate", throwIfNotFound: true);
        m_GolfSwing_StopGolfing = m_GolfSwing.FindAction("StopGolfing", throwIfNotFound: true);
        m_GolfSwing_MousePosition = m_GolfSwing.FindAction("MousePosition", throwIfNotFound: true);
        m_GolfSwing_MouseDelta = m_GolfSwing.FindAction("MouseDelta", throwIfNotFound: true);
    }

    ~@GolfControls()
    {
        UnityEngine.Debug.Assert(!m_PlayerGeneral.enabled, "This will cause a leak and performance issues, GolfControls.PlayerGeneral.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_GolfSwing.enabled, "This will cause a leak and performance issues, GolfControls.GolfSwing.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerGeneral
    private readonly InputActionMap m_PlayerGeneral;
    private List<IPlayerGeneralActions> m_PlayerGeneralActionsCallbackInterfaces = new List<IPlayerGeneralActions>();
    private readonly InputAction m_PlayerGeneral_Move;
    private readonly InputAction m_PlayerGeneral_StartGolfing;
    private readonly InputAction m_PlayerGeneral_Mantle;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerGeneral".
    /// </summary>
    public struct PlayerGeneralActions
    {
        private @GolfControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerGeneralActions(@GolfControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerGeneral/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_PlayerGeneral_Move;
        /// <summary>
        /// Provides access to the underlying input action "PlayerGeneral/StartGolfing".
        /// </summary>
        public InputAction @StartGolfing => m_Wrapper.m_PlayerGeneral_StartGolfing;
        /// <summary>
        /// Provides access to the underlying input action "PlayerGeneral/Mantle".
        /// </summary>
        public InputAction @Mantle => m_Wrapper.m_PlayerGeneral_Mantle;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerGeneral; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerGeneralActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerGeneralActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerGeneralActions" />
        public void AddCallbacks(IPlayerGeneralActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerGeneralActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerGeneralActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @StartGolfing.started += instance.OnStartGolfing;
            @StartGolfing.performed += instance.OnStartGolfing;
            @StartGolfing.canceled += instance.OnStartGolfing;
            @Mantle.started += instance.OnMantle;
            @Mantle.performed += instance.OnMantle;
            @Mantle.canceled += instance.OnMantle;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerGeneralActions" />
        private void UnregisterCallbacks(IPlayerGeneralActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @StartGolfing.started -= instance.OnStartGolfing;
            @StartGolfing.performed -= instance.OnStartGolfing;
            @StartGolfing.canceled -= instance.OnStartGolfing;
            @Mantle.started -= instance.OnMantle;
            @Mantle.performed -= instance.OnMantle;
            @Mantle.canceled -= instance.OnMantle;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerGeneralActions.UnregisterCallbacks(IPlayerGeneralActions)" />.
        /// </summary>
        /// <seealso cref="PlayerGeneralActions.UnregisterCallbacks(IPlayerGeneralActions)" />
        public void RemoveCallbacks(IPlayerGeneralActions instance)
        {
            if (m_Wrapper.m_PlayerGeneralActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerGeneralActions.AddCallbacks(IPlayerGeneralActions)" />
        /// <seealso cref="PlayerGeneralActions.RemoveCallbacks(IPlayerGeneralActions)" />
        /// <seealso cref="PlayerGeneralActions.UnregisterCallbacks(IPlayerGeneralActions)" />
        public void SetCallbacks(IPlayerGeneralActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerGeneralActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerGeneralActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerGeneralActions" /> instance referencing this action map.
    /// </summary>
    public PlayerGeneralActions @PlayerGeneral => new PlayerGeneralActions(this);

    // GolfSwing
    private readonly InputActionMap m_GolfSwing;
    private List<IGolfSwingActions> m_GolfSwingActionsCallbackInterfaces = new List<IGolfSwingActions>();
    private readonly InputAction m_GolfSwing_Swing;
    private readonly InputAction m_GolfSwing_PracticeSwing;
    private readonly InputAction m_GolfSwing_Rotate;
    private readonly InputAction m_GolfSwing_StopGolfing;
    private readonly InputAction m_GolfSwing_MousePosition;
    private readonly InputAction m_GolfSwing_MouseDelta;
    /// <summary>
    /// Provides access to input actions defined in input action map "GolfSwing".
    /// </summary>
    public struct GolfSwingActions
    {
        private @GolfControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GolfSwingActions(@GolfControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GolfSwing/Swing".
        /// </summary>
        public InputAction @Swing => m_Wrapper.m_GolfSwing_Swing;
        /// <summary>
        /// Provides access to the underlying input action "GolfSwing/PracticeSwing".
        /// </summary>
        public InputAction @PracticeSwing => m_Wrapper.m_GolfSwing_PracticeSwing;
        /// <summary>
        /// Provides access to the underlying input action "GolfSwing/Rotate".
        /// </summary>
        public InputAction @Rotate => m_Wrapper.m_GolfSwing_Rotate;
        /// <summary>
        /// Provides access to the underlying input action "GolfSwing/StopGolfing".
        /// </summary>
        public InputAction @StopGolfing => m_Wrapper.m_GolfSwing_StopGolfing;
        /// <summary>
        /// Provides access to the underlying input action "GolfSwing/MousePosition".
        /// </summary>
        public InputAction @MousePosition => m_Wrapper.m_GolfSwing_MousePosition;
        /// <summary>
        /// Provides access to the underlying input action "GolfSwing/MouseDelta".
        /// </summary>
        public InputAction @MouseDelta => m_Wrapper.m_GolfSwing_MouseDelta;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GolfSwing; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GolfSwingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GolfSwingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GolfSwingActions" />
        public void AddCallbacks(IGolfSwingActions instance)
        {
            if (instance == null || m_Wrapper.m_GolfSwingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GolfSwingActionsCallbackInterfaces.Add(instance);
            @Swing.started += instance.OnSwing;
            @Swing.performed += instance.OnSwing;
            @Swing.canceled += instance.OnSwing;
            @PracticeSwing.started += instance.OnPracticeSwing;
            @PracticeSwing.performed += instance.OnPracticeSwing;
            @PracticeSwing.canceled += instance.OnPracticeSwing;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @StopGolfing.started += instance.OnStopGolfing;
            @StopGolfing.performed += instance.OnStopGolfing;
            @StopGolfing.canceled += instance.OnStopGolfing;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GolfSwingActions" />
        private void UnregisterCallbacks(IGolfSwingActions instance)
        {
            @Swing.started -= instance.OnSwing;
            @Swing.performed -= instance.OnSwing;
            @Swing.canceled -= instance.OnSwing;
            @PracticeSwing.started -= instance.OnPracticeSwing;
            @PracticeSwing.performed -= instance.OnPracticeSwing;
            @PracticeSwing.canceled -= instance.OnPracticeSwing;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @StopGolfing.started -= instance.OnStopGolfing;
            @StopGolfing.performed -= instance.OnStopGolfing;
            @StopGolfing.canceled -= instance.OnStopGolfing;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GolfSwingActions.UnregisterCallbacks(IGolfSwingActions)" />.
        /// </summary>
        /// <seealso cref="GolfSwingActions.UnregisterCallbacks(IGolfSwingActions)" />
        public void RemoveCallbacks(IGolfSwingActions instance)
        {
            if (m_Wrapper.m_GolfSwingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GolfSwingActions.AddCallbacks(IGolfSwingActions)" />
        /// <seealso cref="GolfSwingActions.RemoveCallbacks(IGolfSwingActions)" />
        /// <seealso cref="GolfSwingActions.UnregisterCallbacks(IGolfSwingActions)" />
        public void SetCallbacks(IGolfSwingActions instance)
        {
            foreach (var item in m_Wrapper.m_GolfSwingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GolfSwingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GolfSwingActions" /> instance referencing this action map.
    /// </summary>
    public GolfSwingActions @GolfSwing => new GolfSwingActions(this);
    private int m_KeyboardAndMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardAndMouseScheme
    {
        get
        {
            if (m_KeyboardAndMouseSchemeIndex == -1) m_KeyboardAndMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardAndMouse");
            return asset.controlSchemes[m_KeyboardAndMouseSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerGeneral" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerGeneralActions.AddCallbacks(IPlayerGeneralActions)" />
    /// <seealso cref="PlayerGeneralActions.RemoveCallbacks(IPlayerGeneralActions)" />
    public interface IPlayerGeneralActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "StartGolfing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStartGolfing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mantle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMantle(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GolfSwing" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GolfSwingActions.AddCallbacks(IGolfSwingActions)" />
    /// <seealso cref="GolfSwingActions.RemoveCallbacks(IGolfSwingActions)" />
    public interface IGolfSwingActions
    {
        /// <summary>
        /// Method invoked when associated input action "Swing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PracticeSwing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPracticeSwing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "StopGolfing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStopGolfing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MousePosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMousePosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MouseDelta" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseDelta(InputAction.CallbackContext context);
    }
}
